# GitHub Labels - Lvlup.Build
#
# Base labels from lvlup-sw/.github/labels-base.yml
# plus domain-specific scope labels for this repo.
#
# Sync: gh label sync --force

# Type Labels - What kind of work is this?
- name: "type:bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "type:feature"
  color: "a2eeef"
  description: "New feature or enhancement"

- name: "type:docs"
  color: "0075ca"
  description: "Documentation improvements"

- name: "type:chore"
  color: "fef2c0"
  description: "Maintenance, dependencies, CI"

- name: "type:question"
  color: "d876e3"
  description: "Question or discussion"

# Status Labels - What's the current state?
- name: "status:triage"
  color: "ededed"
  description: "Needs initial review"

- name: "status:blocked"
  color: "b60205"
  description: "Blocked by external factor"

- name: "status:stale"
  color: "ffffff"
  description: "No activity, will auto-close"

# Priority Labels - How urgent is this?
- name: "priority:high"
  color: "d93f0b"
  description: "Address soon"

- name: "priority:low"
  color: "0e8a16"
  description: "Nice to have"

# Source Labels - Where did this issue come from?
- name: "source:jules"
  color: "7C3AED"
  description: "Automated finding from Jules scan"

# Scope Labels - Domain-specific to Lvlup.Build
- name: "scope:analyzers"
  color: "c5def5"
  description: "Analyzer packages or rules"

- name: "scope:props"
  color: "c5def5"
  description: "Build props, targets, or MSBuild config"

- name: "scope:stylecop"
  color: "c5def5"
  description: "StyleCop configuration"

- name: "scope:globalconfig"
  color: "c5def5"
  description: "Global analyzer config rules"
